### ISSUE TITLE
SAP2000_Toolkit: dissallow pulling results with simple FilterRequest

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/SAP2000_Toolkit#128]
#### Broken rules:
Results to be pulled by result requests and not simple filter requests.

#### Suggestions to restore compliance:
1. Delete method ReadResults()
2. Call Modules.Structure.ErrorMessages.ReadResultsError() from IRead()

**Comment by IsakNaslundBh** [comment]
Related to https://github.com/BHoM/BHoM_Adapter/issues/240. Putting note here to link up with other issues.

**Comment by maryannewachter** [comment]
SAP2000_Toolkit does not implement filter requests for pulling results (pulling results is a fairly recent feature), so this just needs to be updated to throw the error if it is attempted once the BHoM Adapter issue is closed.
