### ISSUE TITLE
GravityLoad Push & Pull implementation

### ISSUE THREAD

**Issue by jean-lucjacksonBH** [BHoM/SAP2000_Toolkit#130]
#### Description:
Push is currently improperly implemented, no Pull implementation.

- [ ] correct Push implementation: change from SetLoad(GravityLoad, replace) --> CreateLoad(GravityLoad)
- [ ] Add ability to Pull SAP's GravityLoad for each load pattern (BHoM Loadcase)

**Comment by finnickkim** [comment]
```

```
