### ISSUE TITLE
BarResultRequest divisions not working

### ISSUE THREAD

**Issue by enarhi** [BHoM/SAP2000_Toolkit#171]
#### Description:
BarResultRequest currently returns the sap division amount  no matter what is input into the divisions parameter. It is also prohibitively slow for large result sets, partly due to id handling that we may be able to optimize.

**Comment by JosefTaylor** [comment]
Unfortunately, SAP doesn't allow us to change output stations when the model is locked. The workaround would be to set the bar automesh to the desired number of divisions (which can be done through SAP fragments now, I believe) I'm revising the code to reflect this, letting the user know we're ignoring that input and making sure the results output reflects reality. This also allows removal of a couple API calls which weren't doing anything, which will hopefully speed things up a little bit. I'm going to create a second issue for the speed issue.
