### ISSUE TITLE
Cannot Pull or Push Rigid Links to SAP2000 v21

### ISSUE THREAD

**Issue by WilsonKung** [BHoM/SAP2000_Toolkit#188]
#### Description:
It seems that using SAP2000 v21 with BHoM Beta V.4.0.1.0, rigid links elements cannot be Pull or Push from analysis model.

#### Expected behaviour:
Be able to Pull or Push Rigid links elements from analysis model.

**Comment by JosefTaylor** [comment]
Hi @WilsonKung, can you put up a screenshot or a copy of your script? Rigid Links have been implemented, so I'm curious what kind of trouble you're having.

**Comment by WilsonKung** [comment]
Hi Josef, Maryanne,
Thanks for your response.
I got the rigid link to push into SAP2000 properly this morning.

It turns out that the .json model file I was provided was not made from the same version of BHoM. (i.e. BHoM installer v4.0 while the .json file was creating using BHoM v3.0). So it was not able to push the rigid links into the software.

Thanks.

**Comment by JosefTaylor** [comment]
ah, I see- however, your issue led us to discover some major issues with it, so we've got a PR going to fix it. I re-opened the issue and it will be closed when the PR is merged. Thanks!
