### ISSUE TITLE
SAP2000_Engine: JoinRigidLink() and SplitRigidLink() are not compliant for public methods

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/SAP2000_Toolkit#190]
#### Broken rules:
Join and Split rigid link methods are public, but lack descriptions. JoinRigidLink() also has an issue in Grasshopper where the component does not get list access, causing it to fail.

#### Suggestions to restore compliance:

Two options for fixing:
1. Make them private - for the most part these are not needed in the public space, and if they are, they should be promoted to Structure_Engine.
2. Give them descriptions and fix the grasshopper issues

**Comment by FraserGreenroyd** [comment]
@JosefTaylor is the Grasshopper issue related to https://github.com/BHoM/Grasshopper_Toolkit/issues/518 ? Not sure, just basing off the opening statement about list access.

**Comment by JosefTaylor** [comment]
> 
> 
> @JosefTaylor is the Grasshopper issue related to [BHoM/Grasshopper_Toolkit#518](https://github.com/BHoM/Grasshopper_Toolkit/issues/518) ? Not sure, just basing off the opening statement about list access.

hmm, possible. I think this isn't an issue of versioning, but it ends up with the same problem, that the method takes a list, but GH doesn't give it a list.

**Comment by FraserGreenroyd** [comment]
It appears that over time this issue was resolved to give more information so I'm considering this complete for now 😄
