### ISSUE TITLE
Verification of results for structural adapters

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/SAP2000_Toolkit#192]
#### Definition of the test :

I've produced a script to create two (for now) simple models:
- A simply supported beam,
- A free standing column

A number of different loads are applied:
- Bar uniformly distributed load
- Shear Y and Shear Z applied at mid span
- Torsion applied at free end
- Axial force applied at free end

For this toolkit can you please run the script to create the model, analyse the model and verify that the results are pulled.

This is also a good opportunity to ensure the results follow the [BHoM's Structural Conventions](https://github.com/BHoM/documentation/wiki/BHoM-Structural-Conventions). 

Please save your model in an appropriate folder in [this location](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/16_Test%20Data/Structural%20Models%20for%20Results%20Verificaiton/Models?csf=1&web=1&e=kMCbj7).

The script to push the generic models[ can be found here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/16_Test%20Data/Structural%20Models%20for%20Results%20Verificaiton?csf=1&web=1&e=mGevfI).

Also it should be noted that you will be required to reinitialise the `AdapterId` components (I've highlighted them in red) - see here for the issue: https://github.com/BHoM/BHoM_Adapter/issues/283.

**Comment by peterjamesnugent** [comment]
It also worth noting that the models I have created are in SI Units - so unless this toolkit implements the Units_Engine it should also be in SI Units to allow easy comparison of results between calculated and expected values.

**Comment by maryannewachter** [comment]
LGTM. Note that there is an issue with SAP2000 currently pushing all the loads at once that I'm troubleshooting with @JosefTaylor.
