### ISSUE TITLE
Versioning failure for SAP2000ActionConfig

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/SAP2000_Toolkit#206]
Versioning for `SAP2000ActionConfig` is broken by the rename to `SAP2000PushConfig` in [this PR](https://github.com/BHoM/SAP2000_Toolkit/pull/204). Needs resolving critically before the beta and beta testing.

**Comment by JosefTaylor** [comment]
oops, forgot about that bit. I can fix in my current PR.
