### ISSUE TITLE
Readme out of date

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/SAP2000_Toolkit#255]
#### What is missing/incorrect?

Versions of SAP supported
Object Relations Table

**Comment by melsawy93** [comment]
Is it true that only SAP2000 V21 is currently supported?

**Comment by JosefTaylor** [comment]
Hi @melsawy93, we're supporting v21 and anything more recent - CSI changed their API in v21 so that we don't need to support specific versions, but it only works with v21 and beyond.
