### ISSUE TITLE
SAP2000 Adapter fails for Rhino 8 due to .Net change

### ISSUE THREAD

**Issue by enarhi** [BHoM/SAP2000_Toolkit#299]
#### Description:
When using SAP2000 Adapter with Rhino 8 it fails due to the use of the `Marshal.GetActivgeObject` method which has been phased out, as noted at https://github.com/orgs/BHoM/discussions/1596.

A workaround is available as described at https://forum.evolvelab.io/t/rhino-8-veras-workaround/4992 in order to force Net Framework usage for Rhino, but this is not ideal.

**Comment by FraserGreenroyd** [comment]
Just to capture @enarhi at the moment BHoM has not been rolled out with Rhino 8 formally, I'm aware of some changes to the Rhino 8/Grasshopper way of working that might require a few changes to be implemented - so I'd possibly hold off on making any adapter specific fixes unless they're really niche/small and will still work in Rhino 6/7 (the current versions we support for Rhino).

At some point when we begin the checks and upgrades if we're lucky it'll be similar to Rhino 7 as from 5/6 was but until we've checked that... 😟
