### ISSUE TITLE
SAP2000_Toolkit: Push Gravity Loads

### ISSUE THREAD

**Issue by emidio-piermarini** [BHoM/SAP2000_Toolkit#66]
Seems that the creating of gravity loads uses "SetLoad" whereas all other load creation methods are using "CreateLoad".  Is this a mistake @JosefTaylor @enarhi 

public void SetLoad(GravityLoad gravityLoad, bool replace)

**Comment by JosefTaylor** [comment]
Yep, that's a hold-over from earlier code, since it's almost never used in practice. Should be addressed in #88  Thanks!
